### ISSUE TITLE
route not working properly

### ISSUE THREAD

**Issue by Kulyniak** [d-alejandro/laravel-code-examples#5]
in your project in routes there is routes orders, but when i try to write it in browser in search bar, i get no found

**Comment by d-alejandro** [comment]
Run tests to make sure the application works correctly. You do not need to use a browser to access the application, as the application only works in API mode. If you have not yet mastered working with the application through feature tests, then I advise you to send requests through Postman.

**Comment by d-alejandro** [comment]
Route by default

`http://localhost:8081/api/orders/10000001`

**Comment by d-alejandro** [comment]
Route for order list

`http://localhost:8081/api/orders?start=0&end=2&sort_column=id&sort_type=asc`
